<?php
define('REDIRECT_TIMEOUT', 2);
define('MARIADB_USERNAME', 'ENTER_MYSQL_USERNAME_HERE');
define('MARIADB_PASSWORD', 'ENTER_MYSQL_PASSWORD_HERE');
define('MARIADB_SERVER_NAME', 'ENTER_MYSQL_HOST_HERE');
define('MARIADB_DATABASE_NAME', 'ENTER_MYSQL_DATABASE_NAME_HERE');
?>
